msgid ""
msgstr ""
"Project-Id-Version: 6dbd8a386c58cbb3cf8bf6a67e82186a\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-06-20 12:30+0200\n"
"PO-Revision-Date: 2022-06-30 08:18\n"
"Last-Translator: Greg Kempe (longhotsummer)\n"
"Language-Team: Portuguese\n"
"Language: pt_PT\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: crowdin.com\n"
"X-Crowdin-Project: 6dbd8a386c58cbb3cf8bf6a67e82186a\n"
"X-Crowdin-Language: pt\n"
"X-Crowdin-File: /master/indigo/locale/af/LC_MESSAGES/django.po\n"
"X-Crowdin-Project-ID: 2\n"
"X-Crowdin-File-ID: 12\n"

#: analysis/toc/base.py:14 analysis/work_detail/base.py:48
msgid "Act"
msgstr "Ato"

#: analysis/toc/base.py:15
msgid "Article"
msgstr "artigo"

#: analysis/toc/base.py:16
msgid "By-law"
msgstr "Sub-lei"

#: analysis/toc/base.py:17
msgid "Chapter"
msgstr "Capítulo"

#: analysis/toc/base.py:18
msgid "Government Notice"
msgstr "Aviso do Governo"

#: analysis/toc/base.py:19
msgid "Part"
msgstr "Parte"

#: analysis/toc/base.py:20
msgid "Section"
msgstr "Turma"

#: analysis/toc/base.py:21
msgid "Preface"
msgstr "Prefácio"

#: analysis/toc/base.py:22
msgid "Preamble"
msgstr "Preâmbulo"

#: analysis/work_detail/base.py:34
#, python-format
msgid "%(type)s %(number)s of %(year)s"
msgstr "%(type)s %(number)s de %(year)s"

#: analysis/work_detail/base.py:57
#, python-format
msgid "Chapter %(cap)s"
msgstr "Capítulo %(cap)s"

#: bulk_creator.py:171
#, python-format
msgid "Error talking to Google Sheets: %s"
msgstr "Erro ao conversar com Google Sheets: %s"

#: bulk_creator.py:178
msgid "Your sheet did not import successfully; please check that you have link sharing ON (Anyone with the link)."
msgstr "Sua folha não foi importada com sucesso; verifique se você tem o link de compartilhamento ON (qualquer um com o link)."

#: bulk_creator.py:211
#, python-format
msgid "Unable to access spreadsheet. Is the URL correct and have you shared it with %s?"
msgstr "Não foi possível acessar a planilha. A URL está correta e você compartilhou-a com %s?"

#: bulk_creator.py:217
#, python-format
msgid "There doesn't appear to be data in sheet %(name)s of %(id)s"
msgstr "Parece que não há dados na folha %(name)s de %(id)s"

#: bulk_creator.py:745
msgid "Link gazette"
msgstr "Link do labirinto"

#: bulk_creator.py:746
msgid "This work's gazette (original publication document) couldn't be linked automatically.\n\n"
"Find it and upload it manually."
msgstr "Este diário de trabalho (documento de publicação original) não pôde ser vinculado automaticamente.\n\n"
"Localize-o e faça o upload manualmente."

#: bulk_creator.py:751
msgid "Import content"
msgstr "Importar conteúdo"

#: bulk_creator.py:752
msgid "Import the content for this work – either the initial publication (usually a PDF of the Gazette) or a later consolidation (usually a .docx file)."
msgstr "Importar o conteúdo deste trabalho – a publicação inicial (geralmente um PDF da Gazette) ou uma consolidação posterior (geralmente um arquivo .docx)."

#: bulk_creator.py:755
msgid "Link commencement (passive)"
msgstr "Início do link (passivo)"

#: bulk_creator.py:756
#, python-format
msgid "It looks like this work was commenced by \"%(commenced_by)s\" on %(date)s (see row %(row_num)s of the spreadsheet), but it couldn't be linked automatically. This work has thus been recorded as 'Not commenced'.\n\n"
"Possible reasons:\n"
"– a typo in the spreadsheet\n"
"– the commencing work doesn't exist on the system.\n\n"
"Please link the commencement date and commencing work manually."
msgstr "Parece que este trabalho foi iniciado por \"%(commenced_by)s\" em %(date)s (veja a linha %(row_num)s da planilha), mas ele não pôde ser vinculado automaticamente. Este trabalho foi assim registado como \"não iniciado”.\n\n"
"Possíveis razões:\n"
"- um erro de digitação na planilha\n"
"- o trabalho inicial não existe no sistema.\n\n"
"Por favor, vincule a data de início e comece a trabalhar manualmente."

#: bulk_creator.py:764
msgid "(unknown)"
msgstr "(desconhecido)"

#: bulk_creator.py:769
msgid "'Commences on' date missing"
msgstr "Data da menção 'Em Falta"

#: bulk_creator.py:770
#, python-format
msgid "It looks like this work commences \"%(commences)s\" (see row %(row_num)s of the spreadsheet), but 'commences_on_date' wasn't given so no action has been taken.\n\n"
"If it should be linked, please do so manually."
msgstr "Parece que esta obra começa \"%(commences)s\" (veja a linha %(row_num)s da planilha), mas 'commences_on_date' não foi dada, portanto nenhuma ação foi tomada.\n\n"
"Caso deva ser vinculado, por favor fazê-lo manualmente."

#: bulk_creator.py:778
msgid "Link commencement (active)"
msgstr "Link inicial (ativo)"

#: bulk_creator.py:779
#, python-format
msgid "It looks like this work commences \"%(commences)s\" on %(date)s (see row %(row_num)s of the spreadsheet), but \"%(commences)s\" wasn't found, so no action has been taken.\n\n"
"Possible reasons:\n"
"– a typo in the spreadsheet\n"
"– the commenced work doesn't exist on the system.\n\n"
"If the commencement should be linked, please do so manually."
msgstr "Parece que este trabalho começa \"%(commences)s\" em %(date)s (veja a linha %(row_num)s da planilha), mas \"%(commences)s\" não foi encontrada, portanto nenhuma ação foi tomada.\n\n"
"razões possíveis:\n"
"- um erro de digitação na planilha\n"
"- o trabalho iniciado não existe no sistema.\n\n"
"Se o início deve ser vinculado, por favor fazê-lo manualmente."

#: bulk_creator.py:792
msgid "Link amendment (active)"
msgstr "Alteração de link (ativa)"

#: bulk_creator.py:796
#, python-format
msgid "It looks like this work amends \"%(amended_work)s\" (see row %(row_num)s of the spreadsheet), but it couldn't be linked automatically.\n\n"
"Possible reasons:\n"
"– a typo in the spreadsheet\n"
"– more than one amended work was listed (it only works if there's one)\n"
"– the amended work doesn't exist on the system.\n\n"
"Please link the amendment manually."
msgstr "Parece que esta tarefa altera \"%(amended_work)s\" (veja a linha %(row_num)s da planilha), mas ela não pode ser conectada automaticamente.\n\n"
"Possíveis razões:\n"
"- um erro de digitação na planilha\n"
"- mais de um trabalho alterado foi listado (só funciona se houver uma)\n"
"- o trabalho alterado não existe no sistema.\n\n"
"Por favor, vincule a alteração manualmente."

#: bulk_creator.py:809
msgid "Link amendment (passive)"
msgstr "Alteração de link (passivo)"

#: bulk_creator.py:813
#, python-format
msgid "It looks like this work is amended by \"%(amending_work)s\" (see row %(row_num)s of the spreadsheet), but it couldn't be linked automatically.\n\n"
"Possible reasons:\n"
"– a typo in the spreadsheet\n"
"– more than one amending work was listed (it only works if there's one)\n"
"– the amending work doesn't exist on the system.\n\n"
"Please link the amendment manually."
msgstr "Parece que esta obra é alterada por \"%(amending_work)s\" (veja a linha %(row_num)s da planilha), mas ela não pode ser conectada automaticamente.\n\n"
"Possíveis razões:\n"
"- um erro de digitação da planilha\n"
"- mais de um trabalho rectificativo foi listado (só funciona se houver uma)\n"
"- o trabalho rectificativo não existe no sistema.\n\n"
"Por favor, vincule a alteração manualmente."

#: bulk_creator.py:826
msgid "Link amendment (pending commencement)"
msgstr "Alteração de link (adaptação pendente)"

#: bulk_creator.py:827
#, python-format
msgid "It looks like this work amends %(amended_title)s (%(numbered_title)s), but it couldn't be linked automatically because this work hasn't commenced yet (so there's no date for the amendment).\n\n"
"Please link the amendment manually (and apply it) when this work comes into force."
msgstr "Parece que este trabalho representa uma alteração %(amended_title)s (%(numbered_title)s), mas ele não pode ser associado automaticamente porque este trabalho ainda não começou (então não há data para a alteração).\n\n"
"Por favor vincule a emenda manualmente (e aplique-la) quando este trabalho entrar em vigor."

#: bulk_creator.py:835
msgid "Apply amendment"
msgstr "Aplicar emenda"

#: bulk_creator.py:836
#, python-format
msgid "Apply the amendments made by %(amending_title)s (%(numbered_title)s) on %(date)s.\n\n"
"The amendment has already been linked, so start at Step 3 of https://docs.laws.africa/managing-works/amending-works."
msgstr "Aplicar as alterações feitas por %(amending_title)s (%(numbered_title)s) em %(date)s.\n\n"
"A alteração já foi vinculada, então comece na Etapa 3 de https://docs.laws.africa/managing-works/amending-works."

#: bulk_creator.py:845 bulk_creator.py:882
msgid "Link repeal"
msgstr "Rejeição de link"

#: bulk_creator.py:846
#, python-format
msgid "It looks like this work was repealed by \"%(repealed_by)s\" (see row %(row_num)s of the spreadsheet), but it couldn't be linked automatically.\n\n"
"Possible reasons:\n"
"– a typo in the spreadsheet\n"
"– the repealing work doesn't exist on the system.\n\n"
"Please link the repeal manually."
msgstr "Parece que esta obra foi revogada pelo\"%(repealed_by)s\" (veja a linha %(row_num)s da planilha), mas ela não pôde ser conectada automaticamente.\n\n"
"Possíveis razões:\n"
"- um erro de digitação na planilha\n"
"- o trabalho de revogação não existe no sistema.\n\n"
"Por favor vincule a revogação manualmente."

#: bulk_creator.py:858
msgid "Check / update repeal"
msgstr "Verificar / atualizar revogação"

#: bulk_creator.py:859
#, python-format
msgid "On the spreadsheet (see row %(row_num)s), it says that this work was repealed by %(repealing_title)s (%(repealing_numbered_title)s).\n\n"
"But this work is already listed as having been repealed by %(repealed_by)s (%(repealed_by_numbered_title)s), so the repeal information wasn't updated automatically.\n\n"
"If the old / existing repeal information was wrong, update it manually. Otherwise (if the spreadsheet was wrong), cancel this task with a comment.\n"
msgstr "Na planilha (ver linha %(row_num)s), diz que este trabalho foi revogado por %(repealing_title)s (%(repealing_numbered_title)s).\n\n"
"Mas este trabalho já está listado como tendo sido revogado por %(repealed_by)s (%(repealed_by_numbered_title)s), então as informações de revogação não foram atualizadas automaticamente.\n\n"
"Se a informação de revogação antiga / existente estava errada, atualize-a manualmente. Caso contrário (se a planilha estiver errada), cancele esta tarefa com um comentário.\n"

#: bulk_creator.py:873
msgid "Link repeal (pending commencement)"
msgstr "Revogação de link (início pendente)"

#: bulk_creator.py:874
#, python-format
msgid "It looks like this work repeals %(title)s (%(numbered_title)s), but it couldn't be linked automatically because this work hasn't commenced yet (so there's no date for the repeal).\n\n"
"Please link the repeal manually when this work comes into force."
msgstr "Parece que esta atividade repete %(title)s (%(numbered_title)s), mas ele não pode ser vinculado automaticamente porque este trabalho ainda não começou (então não há data para a revogação).\n\n"
"Por favor vincule a revogação manualmente quando este trabalho entrar em vigor."

#: bulk_creator.py:883
#, python-format
msgid "It looks like this work was repealed by %(title)s (%(numbered_title)s), but it couldn't be linked automatically.\n\n"
"Please link it manually."
msgstr "Parece que este trabalho foi revogado por %(title)s (%(numbered_title)s), mas não pôde ser vinculado automaticamente.\n\n"
"Por favor, vincule-o manualmente."

#: bulk_creator.py:891
msgid "Link primary work"
msgstr "Link do trabalho primário"

#: bulk_creator.py:892
#, python-format
msgid "It looks like this work's primary work is \"%(work)s\" (see row %(row_num)s of the spreadsheet), but it couldn't be linked automatically.\n\n"
"Possible reasons:\n"
"– a typo in the spreadsheet\n"
"– the primary work doesn't exist on the system.\n\n"
"Please link the primary work manually."
msgstr "Parece que o trabalho primário deste trabalho é \"%(work)s\" (veja a linha %(row_num)s da planilha), mas ele não pôde ser conectado automaticamente.\n\n"
"Possíveis razões:\n"
"- um erro de digitação na planilha\n"
"- o trabalho primário não existe no sistema.\n\n"
"Por favor, vincule o trabalho principal manualmente."

#: bulk_creator.py:904
msgid "Link subleg"
msgstr "Link do sub-link"

#: bulk_creator.py:905
#, python-format
msgid "It looks like this work has subleg \"%(subleg)s\" (see row %(row_num)s of the spreadsheet), but it couldn't be linked automatically.\n\n"
"Possible reasons:\n"
"– a typo in the spreadsheet\n"
"– the subleg work doesn't exist on the system.\n\n"
"Please link the subleg work manually."
msgstr "Parece que esta obra tem uma sub-folha \"%(subleg)s\" (veja a linha %(row_num)s da planilha), mas ela não pode ser conectada automaticamente.\n\n"
"Possíveis razões:\n"
"- um erro de digitação na planilha\n"
"- o trabalho subleg não existe no sistema.\n\n"
"Por favor, vincule o produto manualmente."

#: bulk_creator.py:917
msgid "Check / update primary work"
msgstr "Verificar / atualizar o trabalho primário"

#: bulk_creator.py:918
#, python-format
msgid "On the spreadsheet (see row %(row_num)s), it says that this work is subleg under %(title)s (%(numbered_title)s).\n\n"
"But this work is already subleg under %(parent)s, so nothing was done.\n\n"
"Double-check which work this work is subleg of and update it manually if needed. If the spreadsheet was wrong, cancel this task with a comment."
msgstr "Na planilha (ver linha %(row_num)s), diz que este trabalho está subleg abaixo de %(title)s (%(numbered_title)s).\n\n"
"Mas este trabalho já está superado com %(parent)s, então nada foi feito.\n\n"
"Verifique de novo qual trabalho este trabalho é subleg e atualize-o manualmente se necessário. Se a planilha estava errada, cancele esta tarefa com um comentário."

#: bulk_creator.py:930
msgid "Link taxonomy"
msgstr "Link taxonomy"

#: bulk_creator.py:931
#, python-format
msgid "It looks like this work has the following taxonomy: \"%(topics)s\" (see row %(row_num)s of the spreadsheet), but it couldn't be linked automatically.\n\n"
"Possible reasons:\n"
"– a typo in the spreadsheet\n"
"– the taxonomy doesn't exist on the system."
msgstr "Parece que esta obra possui a seguinte taxonomia: \"%(topics)s\" (veja a linha %(row_num)s da planilha), mas ele não pôde ser vinculado automaticamente.\n\n"
"Possíveis razões:\n"
"- um erro de digitação na planilha\n"
"- a taxonomia não existe no sistema."

#: bulk_creator.py:983
#, python-format
msgid "%s (about to be imported)"
msgstr "%s (prestes a ser importado)"

#: pipelines/text.py:81
msgid "We couldn't get any useful text out of the file"
msgstr "Não foi possível obter nenhum texto útil do arquivo"

#: pipelines/text.py:99
msgid "There is not enough text in the document to import. You may need to OCR the file first."
msgstr "Não há texto suficiente no documento para importar. Você pode precisar OCR o arquivo primeiro."

#: settings.py:171
msgid "English"
msgstr "Portuguese-Brazil"

#: settings.py:172
msgid "French"
msgstr "francês"

